apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  title: ${{values.name}}
  description: |
    ${{values.description}}
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{values.destination.owner}}/${{values.destination.repo}}
  links:
    - url: https://github.com/${{values.destination.owner}}/${{values.destination.repo}}
      title: Repository
      icon: github
    - url: https://github.com/${{values.destination.owner}}/${{values.destination.repo}}/tree/main/docs
      title: Docs
      icon: docs
  tags:
    - vue
    - frontend
    - typescript
    - vite
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner}}
  system: ${{values.system}}
